#!/bin/bash
# Generates a difference file between two versions of the schemas and
# uploads it to a 'gist' on Github.
# The schemas of both versions must first have been dumped to file with
#   node build/index.js -t <TAG> -d

# This script uses the command gh from the package github-cli
# which can be downloaded from https://github.com/cli/cli/releases

# Usage:  scripts/diffgen <OLDTAG> <NEWTAG>
# e.g.    scripts/diffgen THUNDERBIRD_109_0b4_RELEASE THUNDERBIRD_115_10_1_RELEASE

FROM=$1
TO=$2

diff -uN APIs/$FROM/metainfo/schema_dump.json APIs/$TO/metainfo/schema_dump.json | gh gist create -f "$FROM-to-$TO.diff" -d "Diff of WebExtension API schemas from the Thunderbird and Firefox source code, between versions $FROM and $TO. Downloaded from https://hg.mozilla.org/try-comm-central and https://hg.mozilla.org/mozilla-unified"

echo "Click the link, click 'Edit', then click 'Make public'"
